/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Lenovo
 */
public class scoreForm extends javax.swing.JFrame {

    /**
     * Creates new form scoreForm
     */
    public scoreForm() {
        initComponents();
        show_scores();
    }
    
    public ArrayList<Student> scoreList(){
        ArrayList<Student> scoreList = new ArrayList<>();
        
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-NRCT8RH\\SQLEXPRESS;databaseName=dbProject;integratedSecurity=true"; 
            Connection con = DriverManager.getConnection(connectionUrl);
            
            String query = "SELECT * FROM Students";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            Student student;
            
            while(rs.next()){
                //errors may occur here. check while testing. note: constraints have been added in sql db. might interfere with inserts.
                // try  making new constructor with only student id and scores if poosible and test.
                student = new Student(rs.getString("[Student ID]"), rs.getString("Name"), rs.getString("[Date of Birth]"), rs.getString("Branch"), rs.getString("[Phone number]"), rs.getString("[Email ID]"), rs.getFloat("subject1"), rs.getFloat("subject2"), rs.getFloat("subject3"), rs.getFloat("subject4"));
                scoreList.add(student);
            }

        }
        
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
        return scoreList;
    }
    
    public void show_scores(){
        ArrayList<Student> list = scoreList();
        DefaultTableModel model = (DefaultTableModel)jTable_scores.getModel();
        Object[] row = new Object[6];
        
        for(int i=0; i<list.size(); i++){
            row[0]=list.get(i).getStudentID();
            row[1]=list.get(i).getSubject1Score();
            row[2]=list.get(i).getSubject2Score();
            row[3]=list.get(i).getSubject3Score();
            row[4]=list.get(i).getSubject4Score();
            row[5]=list.get(i).getCGPA();
            model.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_scores = new javax.swing.JTable();
        updateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        studentId = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        semesterSelect = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        subject1Score = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        subject2Score = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        subject3Score = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        subject4Score = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cgpaLabel = new javax.swing.JLabel();
        IdEmptyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("Search :");

        jTable_scores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Student ID", "Subject 1", "Subject 2", "Subject 3", "Subject 4", "CGPA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_scores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_scoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_scores);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");

        jLabel1.setText("Student ID :");

        studentId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                studentIdKeyReleased(evt);
            }
        });

        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchKeyReleased(evt);
            }
        });

        jLabel8.setText("Semester :");

        semesterSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Semester", "2nd Semester" }));

        jLabel2.setText("Subject 1 :");

        jLabel3.setText("Subject 2 :");

        jLabel4.setText("Subject 3 :");

        jLabel5.setText("Subject 4 :");

        jLabel6.setText("CGPA :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentId)
                            .addComponent(search)
                            .addComponent(semesterSelect, 0, 216, Short.MAX_VALUE)
                            .addComponent(subject1Score)
                            .addComponent(subject2Score)
                            .addComponent(subject3Score)
                            .addComponent(subject4Score)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IdEmptyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cgpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(semesterSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(studentId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IdEmptyLabel)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(subject1Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(subject2Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(subject3Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(subject4Score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cgpaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(backBtn))
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_scoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_scoresMouseClicked
        // TODO add your handling code here:
        int i = jTable_scores.getSelectedRow();
        TableModel model = jTable_scores.getModel();
        studentId.setText(model.getValueAt(i, 0).toString());
        subject1Score.setText(model.getValueAt(i, 1).toString());
        subject2Score.setText(model.getValueAt(i, 2).toString());
        subject3Score.setText(model.getValueAt(i, 3).toString());
        subject4Score.setText(model.getValueAt(i, 4).toString());
        cgpaLabel.setText(model.getValueAt(i, 5).toString());
        
    }//GEN-LAST:event_jTable_scoresMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        
            try{
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                String connectionUrl = "jdbc:sqlserver://DESKTOP-NRCT8RH\\SQLEXPRESS;databaseName=dbProject;integratedSecurity=true";
                Connection con = DriverManager.getConnection(connectionUrl);

                int row = jTable_scores.getSelectedRow();
                String value = (jTable_scores.getModel().getValueAt(row, 0).toString());
                //errors may happen here. also should we keep student id editable?
                
                //change query to fit new table. create table.
                String query = "UPDATE students SET subject1=?, subject2=?, subject3=?, subject4=? WHERE Student ID ="+value;

                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, studentId.getText());
                pst.setString(2, subject1Score.getText());
                pst.setString(3, subject2Score.getText());
                pst.setString(4, subject3Score.getText());
                pst.setString(5, subject4Score.getText());

                pst.executeUpdate();
                DefaultTableModel model = (DefaultTableModel)jTable_scores.getModel();
                model.setRowCount(0);
                show_scores();
                JOptionPane.showMessageDialog(null,"Updated successfully");
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        

    }//GEN-LAST:event_updateBtnActionPerformed

    private void studentIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_studentIdKeyReleased
        // TODO add your handling code here:
        if(studentId.getText().trim().isEmpty()){
            IdEmptyLabel.setText("Student ID cannot be empty");
        }
        else{
            IdEmptyLabel.setText("");
        }
    }//GEN-LAST:event_studentIdKeyReleased

    private void searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyReleased
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://DESKTOP-NRCT8RH\\SQLEXPRESS;databaseName=dbProject;integratedSecurity=true";
            Connection con = DriverManager.getConnection(connectionUrl);

            //error check here.
            String query = "Select subject1, subject2, subject3, subject4 from Students where [Student ID] = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, search.getText());
            ResultSet rs = pst.executeQuery();

            if(rs.next()){

                String sID = search.getText();
                studentId.setText(sID);

                String s1 = rs.getString("subject1");
                subject1Score.setText(s1);
                
                String s2 = rs.getString("subject2");
                subject2Score.setText(s2);
                
                String s3 = rs.getString("subject3");
                subject3Score.setText(s3);
                
                String s4 = rs.getString("subject4");
                subject4Score.setText(s4);

                

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_searchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(scoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(scoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(scoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(scoreForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new scoreForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IdEmptyLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel cgpaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_scores;
    private javax.swing.JTextField search;
    private javax.swing.JComboBox<String> semesterSelect;
    private javax.swing.JTextField studentId;
    private javax.swing.JTextField subject1Score;
    private javax.swing.JTextField subject2Score;
    private javax.swing.JTextField subject3Score;
    private javax.swing.JTextField subject4Score;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
